<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks>net8.0;net9.0</TargetFrameworks>
	</PropertyGroup>
	<PropertyGroup>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<PackageRequireLicenseAcceptance>False</PackageRequireLicenseAcceptance>
		<PackageId>Microsoft.Extensions.Logging.Log4Net.AspNetCore</PackageId>
		<Authors>Huor Swords</Authors>
		<Company></Company>
		<Product>Microsoft.Extensions.Logging.Log4Net.AspNetCore</Product>
		<Description>
			Allows to configure Log4net as Microsoft Extensions Logging handler on any ASP.NET Core application.

			Original code proposal by @anuraj --&gt; https://dotnetthoughts.net/how-to-use-log4net-with-aspnetcore-for-logging/
		</Description>
		<Copyright></Copyright>
		<PackageTags>Microsoft Extensions Logging Log4Net AspNet Core</PackageTags>
		<RootNamespace>Microsoft.Extensions.Logging.Log4Net.AspNetCore</RootNamespace>
		<AssemblyName>Microsoft.Extensions.Logging.Log4Net.AspNetCore</AssemblyName>
		<PackageReleaseNotes>
			#133 - Compatible with .NET 8.0
		</PackageReleaseNotes>
		<PackageProjectUrl>https://github.com/huorswords/Microsoft.Extensions.Logging.Log4Net.AspNetCore</PackageProjectUrl>
		<RepositoryUrl>https://github.com/huorswords/Microsoft.Extensions.Logging.Log4Net.AspNetCore</RepositoryUrl>
		<Version>9.0.0</Version>
		<AssemblyVersion>9.0.0.0</AssemblyVersion>
		<FileVersion>9.0.0.0</FileVersion>
		<SignAssembly>true</SignAssembly>
		<PackageLicenseExpression></PackageLicenseExpression>
		<PackageLicenseFile>LICENSE</PackageLicenseFile>
	</PropertyGroup>
	<PropertyGroup>
		<IncludeSymbols>true</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.SourceLink.AzureRepos.Git" Version="8.0.0" PrivateAssets="All" />
		<PackageReference Include="Microsoft.SourceLink.GitHub" Version="8.0.0" PrivateAssets="All" />
		<PackageReference Include="log4net" Version="3.0.3" />
		<PackageReference Include="Microsoft.Extensions.Logging" Version="9.0.1" />
		<PackageReference Include="Microsoft.Extensions.Configuration" Version="9.0.1" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.0.1" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="9.0.1" />
	</ItemGroup>
	<ItemGroup>
		<None Include="..\..\LICENSE">
			<Pack>True</Pack>
			<PackagePath></PackagePath>
		</None>
	</ItemGroup>
</Project>